# Generated by Django 4.2.5 on 2023-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelogistic',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='trade_logistic.tagpost', verbose_name='Теги'),
        ),
    ]
