# Generated by Django 4.2.5 on 2023-10-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0002_alter_tradelogistic_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelogistic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='trade_logistic.tagpost', verbose_name='Теги'),
        ),
    ]
