# Generated by Django 4.2.5 on 2023-11-15 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0004_alter_tradelogistic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placement', models.DateField(verbose_name='Дата')),
                ('date_docs', models.DateField(verbose_name='Дата доков')),
                ('num_item', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='№ УВР')),
                ('num_transport', models.CharField(db_index=True, max_length=150, verbose_name='№ авто')),
                ('num_doc', models.CharField(max_length=150, verbose_name='№ документов')),
                ('num_nine', models.CharField(max_length=10, verbose_name='№ Длинной "9"')),
                ('num_td', models.CharField(max_length=50, verbose_name='Таможенное разрешение')),
                ('documents', models.CharField(max_length=150, verbose_name='Документы')),
                ('status', models.CharField(max_length=150, verbose_name='Статус УВР')),
                ('path_doc', models.CharField(max_length=150, verbose_name='Скачать PDF')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Примечание', 'verbose_name_plural': 'Примечания'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='tradelogistic',
            options={'ordering': ['time_create'], 'verbose_name': 'Торговая логистика', 'verbose_name_plural': 'Торговая логистика'},
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='note',
            name='readiness',
            field=models.IntegerField(null=True, verbose_name='Готовность'),
        ),
        migrations.AlterField(
            model_name='tradelogistic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, 'Максимум 100 символов')], verbose_name='Слаг'),
        ),
    ]
