# Generated by Django 4.2.5 on 2023-12-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0009_alter_documentinfo_date_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfo',
            name='path_doc',
            field=models.CharField(max_length=255, null=True, verbose_name='Путь'),
        ),
    ]
