# Generated by Django 4.2.5 on 2023-12-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0010_alter_documentinfo_path_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentinfo',
            options={'ordering': ['id'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
