# Generated by Django 4.2.5 on 2024-01-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0013_pdfdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdatabase',
            name='doc_number',
            field=models.CharField(max_length=70, unique=True, verbose_name='Номер уведомления'),
        ),
        migrations.AlterField(
            model_name='pdfdatabase',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя файла'),
        ),
    ]
