# Generated by Django 4.2.5 on 2024-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0014_alter_pdfdatabase_doc_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERIPDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_account', models.CharField(max_length=20, verbose_name='Счёт договора')),
                ('payer_name', models.CharField(max_length=100, unique=True, verbose_name='ФИО плательщика')),
                ('bill_pay', models.IntegerField(null=True, verbose_name='Сумма оплаты')),
                ('date', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('last_read_time', models.DateTimeField(null=True, verbose_name='Время последнего чтения')),
            ],
        ),
    ]
