# Generated by Django 4.2.5 on 2024-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0015_eripdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eripdatabase',
            name='bill_pay',
            field=models.FloatField(null=True, verbose_name='Сумма оплаты'),
        ),
    ]
