# Generated by Django 4.2.5 on 2024-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0016_alter_eripdatabase_bill_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eripdatabase',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата оплаты'),
        ),
    ]
