# Generated by Django 4.2.5 on 2024-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0017_alter_eripdatabase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eripdatabase',
            name='bill_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='eripdatabase',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='eripdatabase',
            name='last_read_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего чтения'),
        ),
    ]
