# Generated by Django 4.2.5 on 2024-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0018_alter_eripdatabase_bill_pay_alter_eripdatabase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eripdatabase',
            name='payer_name',
            field=models.CharField(max_length=100, verbose_name='ФИО плательщика'),
        ),
    ]
