# Generated by Django 4.2.5 on 2024-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0019_alter_eripdatabase_payer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eripdatabase',
            name='id_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Счёт договора'),
        ),
        migrations.AlterField(
            model_name='eripdatabase',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО плательщика'),
        ),
    ]
