# Generated by Django 4.2.5 on 2024-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0021_alter_eripdatabase_id_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinfo',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF файл'),
        ),
    ]
