# Generated by Django 4.2.5 on 2024-06-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_logistic', '0022_documentinfo_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinfo',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='pdf_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='PDF файл'),
        ),
    ]
